baseURL = "https://math.iisc.ac.in/~gadgil/proofs-and-programs-2023/"
languageCode = "en-us"
title = "MA 208: Proof and Programs"
theme = "course"
buildFuture = "true"
[params]
    code = "MA 208"
    course = "Proof and Programs"
    term = "January 2023"
[markup.goldmark.renderer]
unsafe= true